# Netlify build is disabled - using GitHub Actions for building and deployment
# [build]
#   publish = "build/web"
#   command = "bash ./scripts/netlify_build.sh"

[build.environment]
  FLUTTER_VERSION = "3.27.0"
  PUB_CACHE = "$HOME/.pub-cache"
  PATH = "$HOME/flutter/bin:$HOME/.pub-cache/bin:$PATH"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  FLUTTER_VERSION = "3.27.0"

