[build]
  # 方法1: カスタムスクリプト（推奨）
  command = "bash ./scripts/netlify_build.sh"
  # 方法2: 直接Flutterコマンド（シンプル）
  # command = "flutter build web --release"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "18"
  FLUTTER_VERSION = "3.27.0"
  PUB_CACHE = "$HOME/.pub-cache"
  PATH = "$HOME/flutter/bin:$HOME/.pub-cache/bin:$PATH"

[build.image]
  name = "jammy"  # Ubuntu 22.04ベースで安定

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


