// Mocks generated by Mockito 5.4.6 from annotations
// in creditcarddiary/test/features/cards/application/card_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:creditcarddiary/features/cards/domain/card_model.dart' as _i4;
import 'package:creditcarddiary/features/cards/domain/repositories/card_repository.dart'
    as _i2;
import 'package:creditcarddiary/features/cards/domain/repositories/transaction_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardRepository extends _i1.Mock implements _i2.CardRepository {
  MockCardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CreditCard>> getAllCards() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCards, []),
            returnValue: _i3.Future<List<_i4.CreditCard>>.value(
              <_i4.CreditCard>[],
            ),
          )
          as _i3.Future<List<_i4.CreditCard>>);

  @override
  _i3.Future<void> addCard(_i4.CreditCard? card) =>
      (super.noSuchMethod(
            Invocation.method(#addCard, [card]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCard(_i4.CreditCard? card) =>
      (super.noSuchMethod(
            Invocation.method(#updateCard, [card]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertCard(_i4.CreditCard? card) =>
      (super.noSuchMethod(
            Invocation.method(#upsertCard, [card]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCard(String? cardId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCard, [cardId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setCardBudget(
    String? cardId,
    int? year,
    int? month,
    int? amount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setCardBudget, [cardId, year, month, amount]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int?> getCardBudget(String? cardId, int? year, int? month) =>
      (super.noSuchMethod(
            Invocation.method(#getCardBudget, [cardId, year, month]),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i5.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Transaction>> getAllTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransactions, []),
            returnValue: _i3.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<void> addTransaction(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTransaction(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertTransaction(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#upsertTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [transactionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setTotalBudget(int? year, int? month, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#setTotalBudget, [year, month, amount]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int?> getTotalBudget(int? year, int? month) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalBudget, [year, month]),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);
}
